// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: pkg/protocol/plugin.proto

//nolint:gosec // G103: generated protobuf code uses unsafe for performance
package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_protocol_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_plugin_proto_rawDescGZIP(), []int{0}
}

type EventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,5,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,6,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"` // JSON serialized map
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventProto) Reset() {
	*x = EventProto{}
	mi := &file_pkg_protocol_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventProto) ProtoMessage() {}

func (x *EventProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventProto.ProtoReflect.Descriptor instead.
func (*EventProto) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *EventProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventProto) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EventProto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EventProto) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EventProto) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *EventProto) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type ResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	DataJson      string                 `protobuf:"bytes,4,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"` // JSON serialized map
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseProto) Reset() {
	*x = ResponseProto{}
	mi := &file_pkg_protocol_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseProto) ProtoMessage() {}

func (x *ResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseProto.ProtoReflect.Descriptor instead.
func (*ResponseProto) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseProto) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *ResponseProto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ResponseProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResponseProto) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type ContextProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Event          *EventProto            `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	PropertiesJson string                 `protobuf:"bytes,2,opt,name=properties_json,json=propertiesJson,proto3" json:"properties_json,omitempty"` // JSON serialized map
	Responses      []*ResponseProto       `protobuf:"bytes,3,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContextProto) Reset() {
	*x = ContextProto{}
	mi := &file_pkg_protocol_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextProto) ProtoMessage() {}

func (x *ContextProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextProto.ProtoReflect.Descriptor instead.
func (*ContextProto) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ContextProto) GetEvent() *EventProto {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ContextProto) GetPropertiesJson() string {
	if x != nil {
		return x.PropertiesJson
	}
	return ""
}

func (x *ContextProto) GetResponses() []*ResponseProto {
	if x != nil {
		return x.Responses
	}
	return nil
}

type ExecutionDecisionProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShouldExecute bool                   `protobuf:"varint,1,opt,name=should_execute,json=shouldExecute,proto3" json:"should_execute,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionDecisionProto) Reset() {
	*x = ExecutionDecisionProto{}
	mi := &file_pkg_protocol_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionDecisionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionDecisionProto) ProtoMessage() {}

func (x *ExecutionDecisionProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionDecisionProto.ProtoReflect.Descriptor instead.
func (*ExecutionDecisionProto) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutionDecisionProto) GetShouldExecute() bool {
	if x != nil {
		return x.ShouldExecute
	}
	return false
}

func (x *ExecutionDecisionProto) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	BuildTime     string                 `protobuf:"bytes,3,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	MinCliVersion string                 `protobuf:"bytes,4,opt,name=min_cli_version,json=minCliVersion,proto3" json:"min_cli_version,omitempty"`
	MaxCliVersion string                 `protobuf:"bytes,5,opt,name=max_cli_version,json=maxCliVersion,proto3" json:"max_cli_version,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_pkg_protocol_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Metadata) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

func (x *Metadata) GetMinCliVersion() string {
	if x != nil {
		return x.MinCliVersion
	}
	return ""
}

func (x *Metadata) GetMaxCliVersion() string {
	if x != nil {
		return x.MaxCliVersion
	}
	return ""
}

func (x *Metadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Metadata) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

var File_pkg_protocol_plugin_proto protoreflect.FileDescriptor

const file_pkg_protocol_plugin_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/protocol/plugin.proto\x12\x06shared\"\a\n" +
	"\x05Empty\"\xaf\x01\n" +
	"\n" +
	"EventProto\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x05 \x01(\tR\tchannelId\x12#\n" +
	"\rmetadata_json\x18\x06 \x01(\tR\fmetadataJson\"{\n" +
	"\rResponseProto\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1b\n" +
	"\tdata_json\x18\x04 \x01(\tR\bdataJson\"\x96\x01\n" +
	"\fContextProto\x12(\n" +
	"\x05event\x18\x01 \x01(\v2\x12.shared.EventProtoR\x05event\x12'\n" +
	"\x0fproperties_json\x18\x02 \x01(\tR\x0epropertiesJson\x123\n" +
	"\tresponses\x18\x03 \x03(\v2\x15.shared.ResponseProtoR\tresponses\"W\n" +
	"\x16ExecutionDecisionProto\x12%\n" +
	"\x0eshould_execute\x18\x01 \x01(\bR\rshouldExecute\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xe5\x01\n" +
	"\bMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"build_time\x18\x03 \x01(\tR\tbuildTime\x12&\n" +
	"\x0fmin_cli_version\x18\x04 \x01(\tR\rminCliVersion\x12&\n" +
	"\x0fmax_cli_version\x18\x05 \x01(\tR\rmaxCliVersion\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority2\xb6\x01\n" +
	"\x06Plugin\x12E\n" +
	"\rShouldExecute\x12\x14.shared.ContextProto\x1a\x1e.shared.ExecutionDecisionProto\x125\n" +
	"\aProcess\x12\x14.shared.ContextProto\x1a\x14.shared.ContextProto\x12.\n" +
	"\vGetMetadata\x12\r.shared.Empty\x1a\x10.shared.MetadataB?Z=github.com/williamokano/hashicorp-plugin-example/pkg/protocolb\x06proto3"

var (
	file_pkg_protocol_plugin_proto_rawDescOnce sync.Once
	file_pkg_protocol_plugin_proto_rawDescData []byte
)

func file_pkg_protocol_plugin_proto_rawDescGZIP() []byte {
	file_pkg_protocol_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_plugin_proto_rawDesc), len(file_pkg_protocol_plugin_proto_rawDesc))) //nolint:gosec // G103: generated protobuf code
	})
	return file_pkg_protocol_plugin_proto_rawDescData
}

var file_pkg_protocol_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_protocol_plugin_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: shared.Empty
	(*EventProto)(nil),             // 1: shared.EventProto
	(*ResponseProto)(nil),          // 2: shared.ResponseProto
	(*ContextProto)(nil),           // 3: shared.ContextProto
	(*ExecutionDecisionProto)(nil), // 4: shared.ExecutionDecisionProto
	(*Metadata)(nil),               // 5: shared.Metadata
}
var file_pkg_protocol_plugin_proto_depIdxs = []int32{
	1, // 0: shared.ContextProto.event:type_name -> shared.EventProto
	2, // 1: shared.ContextProto.responses:type_name -> shared.ResponseProto
	3, // 2: shared.Plugin.ShouldExecute:input_type -> shared.ContextProto
	3, // 3: shared.Plugin.Process:input_type -> shared.ContextProto
	0, // 4: shared.Plugin.GetMetadata:input_type -> shared.Empty
	4, // 5: shared.Plugin.ShouldExecute:output_type -> shared.ExecutionDecisionProto
	3, // 6: shared.Plugin.Process:output_type -> shared.ContextProto
	5, // 7: shared.Plugin.GetMetadata:output_type -> shared.Metadata
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_protocol_plugin_proto_init() }
func file_pkg_protocol_plugin_proto_init() {
	if File_pkg_protocol_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_plugin_proto_rawDesc), len(file_pkg_protocol_plugin_proto_rawDesc)), //nolint:gosec // G103: generated protobuf code
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protocol_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_plugin_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_plugin_proto_msgTypes,
	}.Build()
	File_pkg_protocol_plugin_proto = out.File
	file_pkg_protocol_plugin_proto_goTypes = nil
	file_pkg_protocol_plugin_proto_depIdxs = nil
}
